apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  selector:
    matchLabels:
      app: docker
  replicas: 2
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker
          image: $IMAGE_NAME:$BUILD_NUMBER  # Replace with correct image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: docker-ssvc
spec:
  selector:
    app: docker
  type: NodePort  # Corrected indentation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Must be between 30000-32767
