apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: docker
          image: vamshi2506/vamshi2506_devops:latest  # Updated with actual image reference
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: docker-ssvc
spec:
  selector:
    app: docker
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
